### ISSUE TITLE
Hide icons with shell theme - Arc(Arc Darker)

### ISSUE THREAD

**Issue by anial-pro** [rliang/gnome-shell-extension-task-icons#4]
Ubuntu 16.04.3 
WM: GNOME Shell 3.18.5
WM Theme: Adwaita
GTK Theme: Arc-Darker [GTK2/3]
Icon Theme: Numix-Circle

Package: arc
Version: 5.21q-4

This problem is precisely in Theme Shell, but whith theme shell - Arc on lock screen icons looks normal.
<a href="http://fastpic.ru/view/94/2017/0826/ce5b5c9a22ace856583bda7422bd5c0c.png.html" target="_blank"><img src="http://i94.fastpic.ru/thumb/2017/0826/0c/ce5b5c9a22ace856583bda7422bd5c0c.jpeg" border="0"></a>

**Comment by rliang** [comment]
The problem seems to be that Arc hides the CSS class "app-menu-icon". I'll probably add an option to change the icons' CSS class.
