### ISSUE TITLE
Bad spacing when not using symbolic icons

### ISSUE THREAD

**Issue by freddyhayward** [rliang/gnome-shell-extension-task-icons#5]
### Expected behavior
Icons should be spaced the same way as the default:
![screenshot from 2017-09-06 09-01-04](https://user-images.githubusercontent.com/13117753/30087187-bb9af482-928e-11e7-8d50-9b65cb03c3ae.png)

### Actual behavior
Icons hve no spacing and look weird.
![screenshot from 2017-09-06 09-01-38](https://user-images.githubusercontent.com/13117753/30087186-bb6218e2-928e-11e7-8b8a-5136ddfd4965.png)

### Steps to reproduce the behavior
Change Icon Style Class option to anything but default.
Happens on both Numix-Square and Adwaita icon themes.

### GNOME version
3.24

**Comment by rliang** [comment]
The Icon Style Class option is meant to fix #4 .

I actually thought styling the class in `~/.config/gtk-3.0/gtk.css` would apply to the icons, but it doesn't seem to be the case.

Unfortunately this all depends on theme support. But perhaps I could add an option to set just the spacing. What do you think?

**Comment by freddyhayward** [comment]
I don't know, I guess a spacing option wouldn't hurt. Before the rewrite, spacing seemed to be fine e.g. in my issue #3.

**Comment by rliang** [comment]
Now you can set `icons-style` to something like `margin-left: 10px; margin-right: 10px` .

**Comment by freddyhayward** [comment]
Works perfectly now - I ended up with a margin of 5px on either side.
